package bankingApp.SpringBoot.model;

public enum CompanySector {

    ICT, CONSULTANCY, CONSTRUCTION_AND_INFRASTRUCTURE, ENERGY, FINANCIAL_SERVICES, WATER_AND_WASTE, INDUSTRY, RETAIL,
    AGRICULTURAL_SECTOR, CATERING, EDUCATION, NON_PROFIT_ORGANIZATION, EDUCATION_AND_TRAINING, HEALTHCARE, TRANSPORT
}
